# Dockerfile.api
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY api ./api
COPY summarization_module ./summarization_module
COPY data ./data

COPY embeddings ./embeddings

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000"]
